name: CFReward
main: me.okunxw.cfreward.CFReward
version: 1.0.0
api-version: 1.16
depend: [Vault]
commands:
  redeem:
    description: Использовать промокод
    usage: /redeem <код>
  cfreward:
    description: Админ-команды для управления промокодами
    usage: /cfreward <add/remove/list>
    permission: cfreward.admin
