name: CFReward
main: me.okunxw.cfreward.CFReward
version: 1.0.0
description: "Плагин для управления промокодами на сервере Minecraft."
author: okunxw
website: "https://github.com/okunxw/CFReward"

api-version: 1.16

depend:
  - Vault
softdepend:
  - LuckPerms
  - PlaceholderAPI

commands:
  cfreward:
    description: "Основная команда для управления промокодами."
    usage: "/cfreward <подкоманда>"
    aliases: [cf, promo]
    permission: cfreward.admin

permissions:
  cfreward.admin:
    description: "Доступ к управлению промокодами."
    default: op
